import type { MenuOnlinePublicMenuDTO } from './types';

export const mockMenuData: MenuOnlinePublicMenuDTO = {
  tenant: {
    id: '1',
    slug: 'restaurante-demo',
    name: 'Restaurante Demo',
  },
  settings: {
    currency: 'BRL',
    showOutOfStock: true,
    showImages: true,
  },
  categories: [
    {
      id: 'cat-1',
      name: 'Burgers',
      description: 'Nossos deliciosos hambúrgueres artesanais',
      sortOrder: 0,
      status: 'active',
      availability: null,
      visibleDelivery: true,
      visibleCounter: true,
      visibleTable: true,
    },
    {
      id: 'cat-2',
      name: 'Pizzas',
      description: 'Pizzas feitas no forno a lenha',
      sortOrder: 1,
      status: 'active',
      availability: null,
      visibleDelivery: true,
      visibleCounter: true,
      visibleTable: true,
    },
    {
      id: 'cat-3',
      name: 'Bebidas',
      description: 'Refrigerantes, sucos e mais',
      sortOrder: 2,
      status: 'active',
      availability: null,
      visibleDelivery: true,
      visibleCounter: true,
      visibleTable: true,
    },
    {
      id: 'cat-4',
      name: 'Sobremesas',
      description: 'Doces irresistíveis',
      sortOrder: 3,
      status: 'active',
      availability: null,
      visibleDelivery: true,
      visibleCounter: true,
      visibleTable: true,
    },
  ],
  products: [
    {
      id: 'prod-1',
      categoryId: 'cat-1',
      sku: 'BURG-001',
      name: 'X-Bacon Especial',
      description: 'Hambúrguer de 180g, bacon crocante, queijo cheddar, alface, tomate e molho especial',
      status: 'active',
      sortOrder: 0,
      basePrice: 28.90,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-1',
          url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
          altText: 'X-Bacon Especial',
          sortOrder: 0,
        },
      ],
      priceVariations: [],
      modifierGroupIds: ['mod-group-1', 'mod-group-2'],
    },
    {
      id: 'prod-2',
      categoryId: 'cat-1',
      sku: 'BURG-002',
      name: 'X-Tudo',
      description: 'Hambúrguer de 180g, bacon, queijo, ovo, presunto, alface, tomate e molho',
      status: 'active',
      sortOrder: 1,
      basePrice: 32.90,
      promoPrice: 29.90,
      promoStartsAt: new Date().toISOString(),
      promoEndsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      images: [
        {
          id: 'img-2',
          url: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
          altText: 'X-Tudo',
          sortOrder: 0,
        },
      ],
      priceVariations: [],
      modifierGroupIds: ['mod-group-1', 'mod-group-2'],
    },
    {
      id: 'prod-3',
      categoryId: 'cat-2',
      sku: 'PIZ-001',
      name: 'Pizza Margherita',
      description: 'Molho de tomate, mussarela, manjericão fresco e azeite',
      status: 'active',
      sortOrder: 0,
      basePrice: 45.00,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-3',
          url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80',
          altText: 'Pizza Margherita',
          sortOrder: 0,
        },
      ],
      priceVariations: [
        {
          id: 'var-1',
          name: 'Pequena (4 fatias)',
          price: 35.00,
          priceDelta: -10.00,
          isDefault: false,
          sortOrder: 0,
          status: 'active',
        },
        {
          id: 'var-2',
          name: 'Média (6 fatias)',
          price: 45.00,
          priceDelta: 0,
          isDefault: true,
          sortOrder: 1,
          status: 'active',
        },
        {
          id: 'var-3',
          name: 'Grande (8 fatias)',
          price: 55.00,
          priceDelta: 10.00,
          isDefault: false,
          sortOrder: 2,
          status: 'active',
        },
      ],
      modifierGroupIds: ['mod-group-3'],
    },
    {
      id: 'prod-4',
      categoryId: 'cat-2',
      sku: 'PIZ-002',
      name: 'Pizza Calabresa',
      description: 'Molho de tomate, mussarela, calabresa, cebola e azeitonas',
      status: 'active',
      sortOrder: 1,
      basePrice: 48.00,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-4',
          url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&q=80',
          altText: 'Pizza Calabresa',
          sortOrder: 0,
        },
      ],
      priceVariations: [
        {
          id: 'var-4',
          name: 'Pequena (4 fatias)',
          price: 38.00,
          priceDelta: -10.00,
          isDefault: false,
          sortOrder: 0,
          status: 'active',
        },
        {
          id: 'var-5',
          name: 'Média (6 fatias)',
          price: 48.00,
          priceDelta: 0,
          isDefault: true,
          sortOrder: 1,
          status: 'active',
        },
        {
          id: 'var-6',
          name: 'Grande (8 fatias)',
          price: 58.00,
          priceDelta: 10.00,
          isDefault: false,
          sortOrder: 2,
          status: 'active',
        },
      ],
      modifierGroupIds: ['mod-group-3'],
    },
    {
      id: 'prod-5',
      categoryId: 'cat-3',
      sku: 'BEB-001',
      name: 'Coca-Cola 350ml',
      description: 'Refrigerante Coca-Cola lata',
      status: 'active',
      sortOrder: 0,
      basePrice: 5.00,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-5',
          url: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=800&q=80',
          altText: 'Coca-Cola',
          sortOrder: 0,
        },
      ],
      priceVariations: [],
      modifierGroupIds: [],
    },
    {
      id: 'prod-6',
      categoryId: 'cat-3',
      sku: 'BEB-002',
      name: 'Suco de Laranja Natural',
      description: 'Suco de laranja fresco 500ml',
      status: 'active',
      sortOrder: 1,
      basePrice: 8.00,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-6',
          url: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&q=80',
          altText: 'Suco de Laranja',
          sortOrder: 0,
        },
      ],
      priceVariations: [],
      modifierGroupIds: [],
    },
    {
      id: 'prod-7',
      categoryId: 'cat-4',
      sku: 'SOB-001',
      name: 'Brownie de Chocolate',
      description: 'Brownie artesanal com pedaços de chocolate',
      status: 'active',
      sortOrder: 0,
      basePrice: 12.00,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-7',
          url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80',
          altText: 'Brownie',
          sortOrder: 0,
        },
      ],
      priceVariations: [],
      modifierGroupIds: [],
    },
    {
      id: 'prod-8',
      categoryId: 'cat-4',
      sku: 'SOB-002',
      name: 'Cheesecake de Frutas Vermelhas',
      description: 'Cheesecake cremoso com calda de frutas vermelhas',
      status: 'active',
      sortOrder: 1,
      basePrice: 15.00,
      promoPrice: null,
      promoStartsAt: null,
      promoEndsAt: null,
      images: [
        {
          id: 'img-8',
          url: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&q=80',
          altText: 'Cheesecake',
          sortOrder: 0,
        },
      ],
      priceVariations: [],
      modifierGroupIds: [],
    },
  ],
  modifierGroups: [
    {
      id: 'mod-group-1',
      name: 'Adicionais',
      description: 'Adicione itens extras ao seu hambúrguer',
      minSelect: 0,
      maxSelect: 10,
      isRequired: false,
      sortOrder: 0,
      status: 'active',
    },
    {
      id: 'mod-group-2',
      name: 'Ponto da Carne',
      description: 'Escolha o ponto da carne',
      minSelect: 1,
      maxSelect: 1,
      isRequired: true,
      sortOrder: 1,
      status: 'active',
    },
    {
      id: 'mod-group-3',
      name: 'Borda',
      description: 'Escolha a borda da sua pizza',
      minSelect: 0,
      maxSelect: 1,
      isRequired: false,
      sortOrder: 0,
      status: 'active',
    },
  ],
  modifierOptions: [
    {
      id: 'mod-opt-1',
      groupId: 'mod-group-1',
      name: 'Bacon Extra',
      priceDelta: 4.00,
      sortOrder: 0,
      status: 'active',
    },
    {
      id: 'mod-opt-2',
      groupId: 'mod-group-1',
      name: 'Queijo Extra',
      priceDelta: 3.50,
      sortOrder: 1,
      status: 'active',
    },
    {
      id: 'mod-opt-3',
      groupId: 'mod-group-1',
      name: 'Cebola Caramelizada',
      priceDelta: 2.00,
      sortOrder: 2,
      status: 'active',
    },
    {
      id: 'mod-opt-4',
      groupId: 'mod-group-1',
      name: 'Ovo',
      priceDelta: 2.50,
      sortOrder: 3,
      status: 'active',
    },
    {
      id: 'mod-opt-5',
      groupId: 'mod-group-2',
      name: 'Mal Passado',
      priceDelta: 0,
      sortOrder: 0,
      status: 'active',
    },
    {
      id: 'mod-opt-6',
      groupId: 'mod-group-2',
      name: 'Ao Ponto',
      priceDelta: 0,
      sortOrder: 1,
      status: 'active',
    },
    {
      id: 'mod-opt-7',
      groupId: 'mod-group-2',
      name: 'Bem Passado',
      priceDelta: 0,
      sortOrder: 2,
      status: 'active',
    },
    {
      id: 'mod-opt-8',
      groupId: 'mod-group-3',
      name: 'Borda Catupiry',
      priceDelta: 8.00,
      sortOrder: 0,
      status: 'active',
    },
    {
      id: 'mod-opt-9',
      groupId: 'mod-group-3',
      name: 'Borda Cheddar',
      priceDelta: 10.00,
      sortOrder: 1,
      status: 'active',
    },
  ],
  combos: [],
};
